spring:
  application:
    name: phone-microservice

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server: 
  port: 8081

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
# error:
#  whitelabel:
#    enabled: false